//
// Created by Cédric Bodet on 27.10.17.
//

#ifndef PATH_PLANNING_DEFINITIONS_H
#define PATH_PLANNING_DEFINITIONS_H

#define MPH_TO_METER_PER_SECOND 0.44704
#define TIMESTEP 0.020

#define MAX_MPH 50.
#define TARGET_MPH 49.

#define TARGET_SPEED (TARGET_MPH*MPH_TO_METER_PER_SECOND)

#endif //PATH_PLANNING_DEFINITIONS_H
